version: "3.9"
services:
  partdb:
    container_name: partdb
    image: jbtronics/part-db1:v1.15.1
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/partdb?serverVersion=${PG_VERSION}&charset=UTF8
      - APP_ENV=docker
      - DEFAULT_LANG=${DEFAULT_LANG}
      - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE}
      - BASE_CURRENCY=${BASE_CURRENCY}
      - INSTANCE_NAME=Part-DB
      - ALLOW_ATTACHMENT_DOWNLOADS=1
      - USE_GRAVATAR=0
      - PROVIDER_LCSC_ENABLED=1
      - TRUSTED_PROXIES=127.0.0.0/8,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/projects:/projects
    ports:
      - ${APP_PORT}:80
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.partdb-web-redirect.redirectscheme.scheme: https
      traefik.http.services.partdb.loadbalancer.server.port: ${APP_PORT}
      # Web
      traefik.http.routers.partdb-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.partdb-insecure.entrypoints: web
      traefik.http.routers.partdb-insecure.service: partdb
      traefik.http.routers.partdb-insecure.middlewares: partdb-web-redirect
      # Websecure
      traefik.http.routers.partdb.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.partdb.entrypoints: websecure
      traefik.http.routers.partdb.service: partdb
      traefik.http.routers.partdb.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.partdb-local-insecure.rule: Host(`partdb.${LOCAL_DOMAIN}`)
      traefik.http.routers.partdb-local-insecure.entrypoints: web
      traefik.http.routers.partdb-local-insecure.service: partdb
      traefik.http.routers.partdb-local-insecure.middlewares: partdb-web-redirect
      # Local domain secure
      traefik.http.routers.partdb-local.rule: Host(`partdb.${LOCAL_DOMAIN}`)
      traefik.http.routers.partdb-local.entrypoints: websecure
      traefik.http.routers.partdb-local.service: partdb
      traefik.http.routers.partdb-local.tls: true
