name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:      # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Sync Fork
        run: |
          git remote add upstream ${{ vars.UPSTREAM_REPO || 'https://github.com/runtipi/runtipi-appstore.git' }}
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
