version: '3.9'

services:
  localai:
    container_name: localai
    image: ${USE_GPU:+localai/localai:latest-gpu-nvidia-cuda-12}${USE_GPU:-localai/localai:latest-cpu}
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8080
    environment:
      - MODELS_PATH=/models
      - DEBUG=${DEBUG:-false}
      - CONTEXT_SIZE=${CONTEXT_SIZE:-2048}
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/models:/models:cached
      - ${APP_DATA_DIR}/data/images:/tmp/generated/images
    command: ${DEFAULT_MODEL:-phi-2}
    networks:
      - tipi_main_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
      restart_policy:
        condition: on-failure
    labels:
      traefik.enable: true
      traefik.http.middlewares.localai-web-redirect.redirectscheme.scheme: https
      traefik.http.services.localai.loadbalancer.server.port: 8080
      # Web
      traefik.http.routers.localai-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.localai-insecure.entrypoints: web
      traefik.http.routers.localai-insecure.service: localai
      traefik.http.routers.localai-insecure.middlewares: localai-web-redirect
      # Websecure
      traefik.http.routers.localai.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.localai.entrypoints: websecure
      traefik.http.routers.localai.service: localai
      traefik.http.routers.localai.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.localai-local-insecure.rule: Host(`localai.${LOCAL_DOMAIN}`)
      traefik.http.routers.localai-local-insecure.entrypoints: web
      traefik.http.routers.localai-local-insecure.service: localai
      traefik.http.routers.localai-local-insecure.middlewares: localai-web-redirect
      # Local domain secure
      traefik.http.routers.localai-local.rule: Host(`localai.${LOCAL_DOMAIN}`)
      traefik.http.routers.localai-local.entrypoints: websecure
      traefik.http.routers.localai-local.service: localai
      traefik.http.routers.localai-local.tls: true

networks:
  tipi_main_network:
    external: true